### PR TITLE
CGP123: Add mainnet.json file

### PR DESCRIPTION
**Pull request by nvtaveras**

### CODE REVIEW

**Review by juanjgiraldoc — APPROVED** [review]

**Review by juanjgiraldoc — APPROVED** [review]

**Review by ericnakagawa — APPROVED** [review]

**Comment by 0xzoz** [comment]
@nvtaveras could you please resolve the conflicts and we will merge

**Comment by nvtaveras** [comment]
> @nvtaveras could you please resolve the conflicts and we will merge

updated!

**Comment by nvtaveras** [comment]
> @nvtaveras could you please resolve the conflicts and we will merge

@0xzoz updated!

**Comment by jmrossy** [comment]
@nvtaveras looks like your `mainnet.json` file is in the wrong place. It should be under a `cgp-x` folder. Can you move it?

**Comment by jmrossy** [comment]
@nvtaveras Actually I'll include this with some other fixes in an upcoming PR, no worries

**Pull request merged**
