### PR TITLE
Merge branch 'main' into gd-gas-proposal

### PR DESCRIPTION
**Pull request by sirpy**
Proposal to add GoodDollar (G$) as a gas token
Two proposals are created the first to add the oracle for the G$ celo price and the second is to add G$ as a gas token

### CODE REVIEW

**Review by juanjgiraldoc — CHANGES_REQUESTED** [review]
@sirpy Please remove files with the number 0084 to be able to merge into CGP-0085 _(CGP-0084 is already merged)_

**Review by willkraft — APPROVED** [review]

**Review by willkraft — CHANGES_REQUESTED** [review]
Did not mean to approve - please see Juan's comment

**Comment by sirpy** [comment]
@juanjgiraldoc @willkraft 
i've modified the numbers to 85 and 88

**Comment by juanjgiraldoc** [comment]
@sirpy please rename files with 88 to 85 your proposal for Good Dollar is the number 85

**Comment by sirpy** [comment]
@juanjgiraldoc done

**Review by juanjgiraldoc — APPROVED** [review]

**Review by 0xzoz — APPROVED** [review]

**Review by 0xzoz — APPROVED** [review]

**Pull request merged**
