### PR TITLE
cgp-0083.md

### PR DESCRIPTION
**Pull request by sholasparks**

### CODE REVIEW

**Review by juanjgiraldoc — CHANGES_REQUESTED** [review]
@sholasparks Can you please upgrade CGP to CGP-0087 _(CGP-0085 and CGP-0086 already taken)_

Also please follow the schema of the CGPs, you are missing some points.

**Comment by sholasparks** [comment]
@juanjgiraldoc Thanks for the feedback, I have just updated the CGP for 83 to 87

**Review by willkraft — APPROVED** [review]

**Review by willkraft — DISMISSED** [review]
Hey @sholasparks, thanks for updating, but since Juan's comment, a new proposal was added as CGP 87. Could you update to 1 above the most recent proposal number? If you do it in the next day or so, it should be 88

**Comment by sholasparks** [comment]
@willkraft  thanks. I’ve updated to CGP 88. If u could review. Thanks kindly

**Comment by juanjgiraldoc** [comment]
@sholasparks sorry for the confusion before last week we receive lot of proposals. Can you please rename again everything to CGP-0083 and we will merge the proposal.

**Comment by sholasparks** [comment]
@juanjgiraldoc ok. Doing so right away

**Review by juanjgiraldoc — APPROVED** [review]

**Review by juanjgiraldoc — APPROVED** [review]

**Comment by sholasparks** [comment]
@willkraft @0xzoz  for visibility. Thanks

**Review by juanjgiraldoc — APPROVED** [review]

**Review by 0xzoz — APPROVED** [review]

**Pull request merged**
