### PR TITLE
Road to cop28

### PR DESCRIPTION
**Pull request by JeanneBloch**
Hi Anna, here is our proposal for Road to COP28 events series (Forum post: https://forum.celo.org/t/proposal-web3-x-sdg-event-proposal-for-road-to-cop28/6225/22).

### CODE REVIEW

**Review by juanjgiraldoc — CHANGES_REQUESTED** [review]
Hello. 
Please include the multisign info like past proposals.

Structure & Multi-Sig

Multisign address: XXXXXXXXXXX

Role	Name	Multisig wallet
XXXXXXX	XXXXXXX	XXXXXXXXX
XXXXXXX	XXXXXX	XXXXXXXX
XXXXXXXXX	XXXXX	XXXXXXXXX

**Comment by JeanneBloch** [comment]
@juanjgiraldoc , yes this is done. Thank you for your help.

**Review by juanjgiraldoc — CHANGES_REQUESTED** [review]
I solved the issue with a new commit, don't worry.

(Please remove this from the Header: _"- <date created on, in ISO 8601 (yyyy-mm-dd) format>"_)

**Review by juanjgiraldoc — APPROVED** [review]

**Comment by JeanneBloch** [comment]
Thank you, @dhruvmalik007 for your amazing support and @juanjgiraldoc

**Review by 0xzoz — APPROVED** [review]

**Pull request merged**
