### PR TITLE
[CGPXX]: Increase Block Gas Limit to 35M

### PR DESCRIPTION
**Pull request by jcortejoso**
Hi Celo Community and Developers,

We'd like to propose increase Celo's Block Size Limit to 35 gas million. This proposal contains the details to support the change. Any comment, question or suggestion is welcomed.

Thank you.

### CODE REVIEW

**Review by willkraft — APPROVED** [review]

**Comment by jcortejoso** [comment]
Hi @Pinotio! Thanks for the suggestion. I have just opened the [post](https://forum.celo.org/t/propose-to-increase-block-gas-limit-to-35-000-000-gas/3267) to discuss in the forum.
Regarding your question, the rationale is summarized in the post. Current performance improvements lets, ceteris paribus, increase the block gas limit. It could be an argument that current network demand seems that can be handle properly with the current gas limit, and that is true, but the network is expanding and in the past we saw high increment of load in a low time lapse, with very few space to reaction in that circumstances. Considering the recent improvements on the celo-blockchain throughput, increasing the blockgaslimit to 35M is a change that can help the network to be ready to process more transactions whenever it is needed, without an impact in the resource consumption we have.

**Comment by diwu1989** [comment]
If we're gonna make a bump, might as well just go all the way double to 50M.
The newest generation of AWS / Azure / GCP VMs that the majority of the current validators use can handle the 50M block no problem (as long as they remember to switch instance type to use the latest gen AMD cpus)

Next year, the new Intel Xeon server cpus will also be out and those should increase the single thread performance even more on top of the latest AMD chips, so 50M block should be no biggie.

**Comment by diwu1989** [comment]
Your benchmark used GCP N2, if you use GCP Tau VM, you'll see what I mean about 50M block being very doable.

**Comment by aaronmboyd** [comment]
Can we roll it through Baklava and do some load testing and see how the validator set performs? If people get thrashed we can check what their specs were and see if the documentation minimum requirements need to be updated.

**Comment by jcortejoso** [comment]
> Your benchmark used GCP N2, if you use GCP Tau VM, you'll see what I mean about 50M block being very doable.
> 
> If you have the benchmark scripts, might as well just benchmark Tau instance on 100M gas just to see how far we can push it on the latest gen cloud VMs.

Thanks for the recommendation. Current tests are run using celotool, so we can test with Tau VM and compare the results. Although for proposing a (more) specific CPU platform I'd say we should be continuous. We'd like to keep network diversity as much as possible, and we should consider hardware that is widely extended in most of major cloud environments but also being able to run locally in workstations (particularly fullnodes). Maybe this is still true with TauVM, I did not have the opportunity to deep too much on it.



> Can we roll it through Baklava and do some load testing and see how the validator set performs? If people get thrashed we can check what their specs were and see if the documentation minimum requirements need to be updated.
> 
> Edit: Testnet detail was in the CGP already =)

Seems to me a great idea. We need to update the `targetDensity` to sync with current mainnet values.
Because of nature of eip-1559, keeping a prolonged block gas consumption over `targetDensity` is very costly, so we'd need to test with ~80% load or update `targetDensity` to ~1 (if we want to test constant ~100% block load)

**Comment by diwu1989** [comment]
`and we should consider hardware that is widely extended in most of major cloud environments but also being able to run locally in workstations (particularly fullnodes)`

Every major cloud provider's latest gen CPU have sufficient performance, and running locally on workstation / laptop actually has a lot more single-threaded performance than the cloud CPUs, so they're actually **more** ready to handle large block size. This is because high core count server CPUs in data centers typically clock anywhere between 2 to 3ghz (and no single thread turbo), whereas consumer chips have single threaded turbo clocks to 3ghz+, with the same amount of IPC.

I think if we're gonna spend the effort to bump gas + get all validators / full node operators to re-examine their hardware (if that's even necessary), then we might as well just straight up double the block size instead of a small increment and get us as much run-way as we can until the bigger engineering changes to Geth.

**Comment by jcortejoso** [comment]
Replaced by https://github.com/celo-org/governance/pull/131

**Pull request closed without merging**
