### PR TITLE
create cgp-0137.md

### PR DESCRIPTION
**Pull request by pepadev**

### CODE REVIEW

**Comment by 0xzoz** [comment]
@cedric-untangled a couple of items to address:

- Proposal id 136 is already in use. You will need to change this to the next proposal ID to avoid conflicts
- The proposal has no payload or specifics for implementation.

**Comment by cedric-untangled** [comment]
> @cedric-untangled a couple of items to address:
> 
> * Proposal id 136 is already in use. You will need to change this to the next proposal ID to avoid conflicts
> * The proposal has no payload or specifics for implementation.

I updated the proposal and added the payload.

**Comment by cedric-untangled** [comment]
@0xzoz  can you help me review it?

**Comment by 0xzoz** [comment]
> @0xzoz can you help me review it?

sorry I missed this @cedric-untangled. The payload is empty still. You will need to populate it to reflect your ask. You can use some of the other proposals as references if needed or you can reach out via discord if you need my help @w3sc

**Comment by 0xzoz** [comment]
@pepadev bumping the above pls

**Comment by 0xzoz** [comment]
Hi @pepadev, As this proposal was originally submitted around a year ago with little correspondence. We are kindly asking your team to please follow the governance process by speaking at a governance call, creating a new forum post and a new PR. One of the team members will shortly follow up on your forum post here: https://forum.celo.org/t/proposal-for-allocating-5m-from-the-celo-community-fund-to-rwa-lending-pools-with-untangled-protocol/6100/6

Please consider the feedback in this PR before submitting again. Particularly regarding the payload json file.

**Pull request closed without merging**
